config/routes.rb
Company::Application.routes.draw do

  captcha_route
    get "main/home" 
    get "news" => "main#news"
    get "dynamic" => "main#dynamic"
    get "intro" => "main#intro"
    get "policy" => "main#policy"
    get "supply" => "main#supply"
    get "product" => "main#product"
    get "tech" => "main#tech"
    get 'detail/:id' => "main#detail"
    get 'pro_detail/:id' => "main#pro_detail"

    post "main/post_list"
    post "main/post_count"
    post "main/inc_visit"
    get "main/search"

    get "admin" => 'admin#home'
    get "admin/post_new"
    get "admin/post_edit/:id" => "admin#post_edit"
    post "admin/post_update"
    get "admin/post/:typecd" =>"admin#post"
    post "admin/post_save"
    post "admin/post_list"
    post "admin/post_remove"
    get "admin/login"
    post "admin/check_login"
    get "admin/logout"
    get "admin/home"
    get "admin/pwd"
    get "admin/link"
    get "admin/link_new"
    get "admin/link_list"
    post "admin/link_remove"
    post "ueditor/imageUp"
    post "ueditor/fileUp"
    get 'admin/link_edit/:id' => "admin#link_edit"
    get "admin/product_new"
    get "admin/product"
    get "admin/product_edit/:id" => "admin#product_edit"
    post "admin/product_list"
    post "admin/up_pic"

  root :to => 'main#home'

end

app/views/admin/home.slim
doctype html
html
  head
    title 后台管理
    =stylesheet_link_tag "themes/default/easyui.css", :media => "all"
    =stylesheet_link_tag "admin", :media => "all"
    =stylesheet_link_tag "themes/icon.css", :media => "all" 
    =javascript_include_tag "jquery"  
    =javascript_include_tag "jquery.form"  
    =javascript_include_tag "admin"       
    =javascript_include_tag "jquery.easyui.min" 
    =csrf_meta_tags
  body.easyui-layout 
    div[data-options="region:'north'" style='height:50px;background-color:#3262A3;color:#FFF'] 
      strong.admintitle 后台管理系统 
      a.logout[href='/admin/logout'] 注销
    div#footer[data-options="region:'south',split:true"] 后台管理
    div#leftm[data-options="region:'west',split:true" title='管理面板']
        div.easyui-accordion[fit="true" border="false"]
          div[title='信息管理'  iconcls="icon-add"] 
            ul.lmenu
              li  
                a[href="javascript:void(0)" url="/admin/post_new"] 添加信息
              -Post.typecd_used.each do |t|                
                li 
                  a[href="javascript:void(0)" url="/admin/post/#{t.cd}"]=t.full_sdesc  
          div[title='产品管理'  iconcls="icon-add"]
            ul.lmenu
              li  
                a[href="javascript:void(0)" url="/admin/product_new"] 产品添加
              li 
                a[href="javascript:void(0)" url="/admin/product"] 产品管理
          div[title='站点管理' iconcls="icon-add"]
            ul.lmenu
              li  
                a[href="javascript:void(0)" url="/admin/pwd"] 登录密码
              li 
                a[href="javascript:void(0)" url="/admin/link"] 友情链接
          
          
    div[region="center" split="true"]
        div#tabs.easyui-tabs[fit="true" border="false"]
          div[title="首页"]
             
javascript:
  $(function () {
    $(".easyui-accordion ul li a").click(function () { 
        var icon=$(this).closest('li').attr("class");
        var url = $(this).attr("url");
        var title = $(this).html();
        var tab = add_tab(title, url,icon); 
    });
  }); 

app/views/admin/link.slim
table#dg

javascript:
  var url={
    list:'/admin/post_list',
    remove:'/admin/post_remove'
  }
  var dg;
  $(function(){
    InitialData(url.list);
    dg.datagrid('load');
  });
  function InitialData(list){
     dg = $('#dg').datagrid({
        url:list,
        fit: true,
        striped:true, 
        rownumbers:true, 
        pagination:true,
        pageList: [10, 20,40 ,100],
        pageSize: 20,
        queryParams: {
          typecd: 'LINK'
        },
        toolbar: [
         {
            text:'添加',
            iconCls: 'icon-add',
            handler: function(){
              Add();
            }
          },{
            text:'编辑',
            iconCls: 'icon-edit',
            handler: function(){
              Edit();
            }
          },{
            text:'删除',
            iconCls: 'icon-remove',
            handler: function(){
              Delete();
            }
          } 
        ],
        columns:[[
            {field:'mid',title:'',checkbox:true},
            {field:'id',title:'ID'},
            {field:'title',title:'网站名'}, 
            {field:'val1',title:'网站链接'}, 
            {field:'insert_time',title:'插入时间'}  
        ]]
     }); 
  }


  function Delete(){  
     var rows = dg.datagrid('getSelections');
     if(rows.length < 1){
        show_msg('提示','请勾选要删除的行');
        return false;
     } 
     $.messager.confirm('提示','你确定删除所选数据？',function(r){
       if(r){  
          var ids = _.map(rows,function(row){return row.id}).join(',');
          $.post(url.remove,{ids:ids},function(data){
            if(data.status){ 
              show_msg('提示','删除数据成功');
              dg.datagrid('reload');
            }else{
              show_msg('提示','删除数据出错');
              dg.datagrid('unselectAll');
            }
          }); 
       }
     }); 
  }

  function Edit(obj){
    var rows = dg.datagrid('getSelections');
     if(rows.length < 1){
        show_msg('提示','请勾选要编辑的行');
        return false;
     } 
     if(rows.length > 1){
        show_msg('提示','请勿勾选多行');
        return false;
     } 
     parent.parent.add_tab('编辑友链：' + rows[0].title + '-' + rows[0].id,'/admin/link_edit/'+rows[0].id,'icon');
  }
   
  function Add(){
    parent.parent.add_tab('添加友链','/admin/link_new/','icon');
  }

app/views/admin/link_edit.slim
=form_tag(admin_post_update_path,method:"post",id:'inform')
  table
    tr 
      td =label_tag(:title,'网站名')
      td =text_field_tag(:title,'',class:'txt',value:"#{@link.title}") 
    tr 
      td =label_tag(:val1,'网站链接')
      td =text_field_tag(:val1,'',class:'txt long',value:"#{@link.val1}") 
    tr
      td =hidden_field_tag(:id,@link.id)
      td =submit_tag('更  新',class:'btn')
javascript:
   $('#inform').validate({ 
      success: "valid",
      rules:{
        title:{
          required:true
        },
        val1:{
          required:true
        }
      },
      messages:{ 
        title:"标题不能为空",
        val1:"链接不能为空"
      },
      submitHandler: function(form) {
        $(form).ajaxSubmit({
           beforeSerialize:function(){},
           success:function(data){
             if(data.status){
               window.parent.frames.slide("更新友链成功！"); 
               
             }else{
               window.parent.frames.alert_error('更新友链失败！')
             } 
           },
           error:function(){
             window.parent.frames.alert_error('更新友链失败！')
           }
        });
      }
    });


app/views/admin/link_new.slim
=form_tag(admin_post_save_path,method:"post",id:'inform')
  table
    tr 
      td =label_tag(:title,'网站名')
      td =text_field_tag(:title,'',class:'txt') 
    tr 
      td =label_tag(:val1,'网站链接')
      td =text_field_tag(:val1,'',class:'txt long') 
    tr
      td =hidden_field_tag(:typecd,'LINK')
      td =submit_tag('添  加',class:'btn')
javascript:
   $('#inform').validate({ 
      success: "valid",
      rules:{
        title:{
          required:true
        },
        val1:{
          required:true
        }
      },
      messages:{ 
        title:"标题不能为空",
        val1:"链接不能为空"
      },
      submitHandler: function(form) {
        $(form).ajaxSubmit({
           beforeSerialize:function(){},
           success:function(data){
             if(data.status){
               window.parent.frames.slide("添加友链成功！"); 
               $(".txt").val(''); 
             }else{
               window.parent.frames.alert_error('添加友链失败！')
             } 
           },
           error:function(){
             window.parent.frames.alert_error('添加友链失败！')
           }
        });
      }
    });


app/views/admin/login.slim
doctype html
html
  head
    title 后台管理-登录  
    =stylesheet_link_tag "base", :media => "all"
    =stylesheet_link_tag "login", :media => "all"    
    =csrf_meta_tags
  body 
    div.login
      form[action="/admin/check_login" method="post" id="inform"]
        div.logo
          div.login_form
            div.user
              input.text_value[placeholder="账号" name="uid" type="text"]
              input.text_value[placeholder="密码" name="pwd" type="password"]
            input.button#submit[type="submit"] 
 

app/views/admin/post.slim
table#dg

javascript:
  var url={
    list:'/admin/post_list',
    remove:'/admin/post_remove'
  }
  var dg;
  $(function(){
    InitialData(url.list);
    dg.datagrid('load');
  });
  function InitialData(list){
     dg = $('#dg').datagrid({
        url:list,
        fit: true,
        striped:true, 
        rownumbers:true, 
        pagination:true,
        pageList: [10, 20,40 ,100],
        pageSize: 20, 
        queryParams: {
          typecd: '#{params[:typecd]}'
        },
        toolbar: [
          {
            text:'添加',
            iconCls: 'icon-add',
            handler: function(){
              Add();
            }
          },{
            text:'编辑',
            iconCls: 'icon-edit',
            handler: function(){
              Edit();
            }
          },{
            text:'删除',
            iconCls: 'icon-remove',
            handler: function(){
              Delete();
            }
          },{
            text:'预览',
            iconCls: 'icon-search',
            handler: function(){
              Preview();
            }
          }
        ],
        columns:[[
            {field:'mid',title:'',checkbox:true},
            {field:'id',title:'ID'},
            {field:'title',title:'标题'}, 
            {field:'visit',title:'访问统计'}, 
            {field:'insert_time',title:'插入时间'},
            {field:'isreco',title:'是否推荐',formatter:function(value,row,index){ 
              if(value=="1"){ 
                return '是'
              }else{
                 return "否";
              }
            }},   
        ]] 
     }); 
  }


  function Delete(){  
     var rows = dg.datagrid('getSelections');
     if(rows.length < 1){
        show_msg('提示','请勾选要删除的行');
        return false;
     } 
     $.messager.confirm('提示','你确定删除所选数据？',function(r){
       if(r){  
          var ids = _.map(rows,function(row){return row.id}).join(',');
          $.post(url.remove,{ids:ids},function(data){
            if(data.status){ 
              show_msg('提示','删除数据成功');
              dg.datagrid('reload');
            }else{
              show_msg('提示','删除数据出错');
              dg.datagrid('unselectAll');
            }
          }); 
       }
     }); 
  }

  function Edit(obj){
    var rows = dg.datagrid('getSelections');
     if(rows.length < 1){
        show_msg('提示','请勾选要编辑的行');
        return false;
     } 
     if(rows.length > 1){
        show_msg('提示','请勿勾选多行');
        return false;
     } 
     parent.parent.add_tab('编辑文章：' + rows[0].title + '-' + rows[0].id,'/admin/post_edit/'+rows[0].id,'icon');
  }
  function Preview(){

  }
  function Add(){
    parent.parent.add_tab('添加信息','/admin/post_new/','icon');
  }

app/views/admin/post_edit.slim
=form_tag(admin_post_update_path,method:"post",id:'inform')
  table
    tr 
      td =label_tag(:title,'标题')
      td =text_field_tag(:title,@post.title,class:'txt long')
    tr
      td =label_tag(:typecd,'类型')
      td =select_tag "typecd", options_from_collection_for_select(Refcd.current('POSTTYP'), "cd", "sdesc",@post.typecd)
    tr 
      td =label_tag(:content,'内容')
      td 
        script#editor[type="text/plain" style="width:1024px;height:500px;"]
          =raw @post.content
    tr 
      td =label_tag(:isreco,'推荐')
      td =check_box_tag "isreco",@post.isreco,@post.isreco == '1'
    tr
      td =hidden_field_tag(:id,@post.id)
      td =submit_tag('更  新',class:'btn')
javascript:
   var editor = UE.getEditor('editor'); 
   
   $('#inform').validate({ 
      success: "valid",
      rules:{
        title:{
          required:true
        }
      },
      messages:{ 
        title:"标题不能为空"
      },
      submitHandler: function(form) {
        $(form).ajaxSubmit({
           beforeSerialize:function(){  
            if($("#isreco")[0].checked){
               $("#isreco").val('1');
            }else{$("#isreco").val('0');} 
           },
           success:function(data){
             if(data.status){
               window.parent.frames.slide("更新文章成功！");  
             }else{
               window.parent.frames.alert_error('更新文章失败！')
             } 
           },
           error:function(){
             window.parent.frames.alert_error('更新文章失败！')
           }
        });
      }
    });


app/views/admin/post_new.slim
=form_tag(admin_post_save_path,method:"post",id:'inform')
  table
    tr 
      td =label_tag(:title,'标题')
      td =text_field_tag(:title,'',class:'txt long')
    tr
      td =label_tag(:typecd,'类型')
      td =select_tag "typecd", options_from_collection_for_select(Post.typecd_used, "cd", "full_sdesc")
    tr 
      td =label_tag(:content,'内容')
      td 
        script#editor[type="text/plain" style="width:1024px;height:500px;"]
    tr 
      td =label_tag(:isreco,'推荐')
      td =check_box_tag "isreco",'0',false
    tr
      td 
      td =submit_tag('添  加',class:'btn')
javascript:
   var editor = UE.getEditor('editor');
   $('#inform').validate({ 
      success: "valid",
      rules:{
        title:{
          required:true
        }
      },
      messages:{ 
        title:"标题不能为空"
      },
      submitHandler: function(form) {
        $(form).ajaxSubmit({
           beforeSerialize:function(){
              if($("#isreco")[0].checked){
               $("#isreco").val('1');
              }else{$("#isreco").val('0');} 
           },
           success:function(data){
             if(data.status){
               window.parent.frames.slide("添加文章成功！"); 
               $("#title").val('');
               editor.setContent('');
             }else{
               window.parent.frames.alert_error('添加文章失败！')
             } 
           },
           error:function(){
             window.parent.frames.alert_error('添加文章失败！')
           }
        });
      }
    });


app/views/admin/product.slim
table#dg

javascript:
  var url={
    list:'/admin/product_list',
    remove:'/admin/post_remove'
  }
  var dg;
  $(function(){
    InitialData(url.list);
    dg.datagrid('load');
  });
  function InitialData(list){
     dg = $('#dg').datagrid({
        url:list,
        fit: true,
        striped:true, 
        rownumbers:true, 
        pagination:true,
        pageList: [10, 20,40 ,100],
        pageSize: 20, 
        queryParams: {
          typecd: '#{params[:typecd]}'
        },
        toolbar: [
          {
            text:'添加',
            iconCls: 'icon-add',
            handler: function(){
              Add();
            }
          },{
            text:'编辑',
            iconCls: 'icon-edit',
            handler: function(){
              Edit();
            }
          },{
            text:'删除',
            iconCls: 'icon-remove',
            handler: function(){
              Delete();
            }
          },{
            text:'预览',
            iconCls: 'icon-search',
            handler: function(){
              Preview();
            }
          }
        ],
        columns:[[
            {field:'mid',title:'',checkbox:true},
            {field:'id',title:'ID'},
            {field:'val1',title:'缩略图',formatter:function(value,row,index){ 
              return "<img src='/upload/product/"+value+"' class='face'/>";
            }},
            {field:'title',title:'产品名'}, 
            {field:'visit',title:'访问统计'}, 
            {field:'insert_time',title:'插入时间'},
            {field:'isreco',title:'是否推荐',formatter:function(value,row,index){ 
              if(value=="1"){ 
                return '是'
              }else{
                 return "否";
              }
            }},   
        ]] 
     }); 
  }


  function Delete(){  
     var rows = dg.datagrid('getSelections');
     if(rows.length < 1){
        show_msg('提示','请勾选要删除的行');
        return false;
     } 
     $.messager.confirm('提示','你确定删除所选数据？',function(r){
       if(r){  
          var ids = _.map(rows,function(row){return row.id}).join(',');
          $.post(url.remove,{ids:ids},function(data){
            if(data.status){ 
              show_msg('提示','删除数据成功');
              dg.datagrid('reload');
            }else{
              show_msg('提示','删除数据出错');
              dg.datagrid('unselectAll');
            }
          }); 
       }
     }); 
  }

  function Edit(obj){
    var rows = dg.datagrid('getSelections');
     if(rows.length < 1){
        show_msg('提示','请勾选要编辑的行');
        return false;
     } 
     if(rows.length > 1){
        show_msg('提示','请勿勾选多行');
        return false;
     } 
     parent.parent.add_tab('编辑文章：' + rows[0].title + '-' + rows[0].id,'/admin/product_edit/'+rows[0].id,'icon');
  }
  function Preview(){

  }
  function Add(){
    parent.parent.add_tab('产品添加','/admin/product_new/','icon');
  }

app/views/admin/product_edit.slim
=form_tag(admin_post_update_path,method:"post",id:'inform')
  table
    tr 
      td =label_tag(:title,'产品名')
      td =text_field_tag(:title,@product.title,class:'txt long')
    tr
      td =label_tag(:val1,'封面图片')
      td =text_field_tag(:val1,@product.val1,class:'txt long')
    tr
      td
      td =file_field_tag 'file_upload'
    tr 
      td =label_tag(:content,'产品信息')
      td 
        script#editor[type="text/plain" style="width:1024px;height:500px;"] 
          =raw @product.content
    tr 
      td =label_tag(:isreco,'推荐')
      td =check_box_tag "isreco",@product.isreco,@product.isreco == '1'
    tr
      td =hidden_field_tag(:id,@product.id)
      td =submit_tag('更  新',class:'btn')
javascript:
   $(function(){
      $("#file_upload").uploadify({ 
        'buttonText' : '上传图片',
        'swf'      : '/assets/common/uploadify.swf',
        'uploader' : '/admin/up_pic',
        'onUploadSuccess' : function(file, data, response) {
            if(data == '0'){alert('上传图片失败，请重试！');}else{
              $('#val1').val(data);
            }
        } 
      });
   })
   var editor = UE.getEditor('editor');

   $('#inform').validate({ 
      success: "valid",
      rules:{
        title:{
          required:true
        },
        val1:{
          required:true
        }
      },
      messages:{ 
        title:"产品标题不能为空",
        val1:"产品图片不能为空"
      },
      submitHandler: function(form) {
        $(form).ajaxSubmit({
           beforeSerialize:function(){
              if($("#isreco")[0].checked){
               $("#isreco").val('1');
              }else{$("#isreco").val('0');} 
           },
           success:function(data){
             if(data.status){
               window.parent.frames.slide("更新产品成功！"); 
               $("#title").val('');
               editor.setContent('');
             }else{
               window.parent.frames.alert_error('更新产品失败！')
             } 
           },
           error:function(){
             window.parent.frames.alert_error('更新产品失败！')
           }
        });
      }
    });


app/views/admin/product_new.slim
=form_tag(admin_post_save_path,method:"post",id:'inform')
  table
    tr 
      td =label_tag(:title,'产品名')
      td =text_field_tag(:title,'',class:'txt long')
    tr
      td =label_tag(:val1,'封面图片')
      td =text_field_tag(:val1,'',class:'txt long')
    tr
      td
      td =file_field_tag 'file_upload'
    tr 
      td =label_tag(:content,'产品信息')
      td 
        script#editor[type="text/plain" style="width:1024px;height:500px;"] 
    tr 
      td =label_tag(:isreco,'推荐')
      td =check_box_tag "isreco",'0',false
    tr
      td =hidden_field_tag(:typecd,'PRODUCT')
      td =submit_tag('添  加',class:'btn')
javascript:
   $(function(){
      $("#file_upload").uploadify({ 
        'buttonText' : '上传图片',
        'swf'      : '/assets/common/uploadify.swf',
        'uploader' : '/admin/up_pic',
        'onUploadSuccess' : function(file, data, response) {
            if(data == '0'){alert('上传图片失败，请重试！');}else{
              $('#val1').val(data);
            }
        } 
      });
   })
   var editor = UE.getEditor('editor');

   $('#inform').validate({ 
      success: "valid",
      rules:{
        title:{
          required:true
        },
        val1:{
          required:true
        }
      },
      messages:{ 
        title:"产品标题不能为空",
        val1:"产品图片不能为空"
      },
      submitHandler: function(form) {
        $(form).ajaxSubmit({
           beforeSerialize:function(){
              if($("#isreco")[0].checked){
               $("#isreco").val('1');
              }else{$("#isreco").val('0');} 
           },
           success:function(data){
             if(data.status){
               window.parent.frames.slide("添加产品成功！"); 
               $("#title").val('');
               $("#val1").val('');
               editor.setContent('');
             }else{
               window.parent.frames.alert_error('添加产品失败！')
             } 
           },
           error:function(){
             window.parent.frames.alert_error('添加产品失败！')
           }
        });
      }
    });
