config/routes.rb
Company::Application.routes.draw do

  captcha_route
    get "main/home" 
    get "news" => "main#news"
    get "dynamic" => "main#dynamic"
    get "intro" => "main#intro"
    get "policy" => "main#policy"
    get "supply" => "main#supply"
    get "product" => "main#product"
    get "tech" => "main#tech"
    get 'detail/:id' => "main#detail"
    get 'pro_detail/:id' => "main#pro_detail"

    post "main/post_list"
    post "main/post_count"
    post "main/inc_visit"
    get "main/search"

    get "admin" => 'admin#home'
    get "admin/post_new"
    get "admin/post_edit/:id" => "admin#post_edit"
    post "admin/post_update"
    get "admin/post/:typecd" =>"admin#post"
    post "admin/post_save"
    post "admin/post_list"
    post "admin/post_remove"
    get "admin/login"
    post "admin/check_login"
    get "admin/logout"
    get "admin/home"
    get "admin/pwd"
    get "admin/link"
    get "admin/link_new"
    get "admin/link_list"
    post "admin/link_remove"
    post "ueditor/imageUp"
    post "ueditor/fileUp"
    get 'admin/link_edit/:id' => "admin#link_edit"
    get "admin/product_new"
    get "admin/product"
    get "admin/product_edit/:id" => "admin#product_edit"
    post "admin/product_list"
    post "admin/up_pic"

  root :to => 'main#home'

end

app/views/layouts/admin.slim
=stylesheet_link_tag "themes/default/easyui.css", :media => "all"
=stylesheet_link_tag "themes/icon.css", :media => "all" 
=stylesheet_link_tag "uploadify", :media => "all"
=stylesheet_link_tag "admin", :media => "all"
=javascript_include_tag "jquery"  
=javascript_include_tag "jquery.form"  
=javascript_include_tag "underscore-min" 
=javascript_include_tag "/ueditor/ueditor.config"
=javascript_include_tag "/ueditor/ueditor.all.min" 
=javascript_include_tag "/ueditor/lang/zh-cn/zh-cn"
=javascript_include_tag "jquery.validate.min"
=javascript_include_tag "admin"        
=javascript_include_tag "jquery.easyui.min" 
=javascript_include_tag "jquery.uploadify" 

=yield

app/views/layouts/application.slim
doctype html
html
  head
    title 运动社区
    =stylesheet_link_tag "application", :media => "all"
    =javascript_include_tag "application" 
    =javascript_include_tag "/ueditor/ueditor.config"
  	=javascript_include_tag "/ueditor/ueditor.all.min" 
  	=javascript_include_tag "/ueditor/lang/zh-cn/zh-cn"
    =csrf_meta_tags
  body
      =yield  

 

app/views/layouts/main.slim
DOCTYPE html
html
  head
    title 名山区香水苗木种植农民专业合作社
    = stylesheet_link_tag   "pagination", :media => "all"
    = stylesheet_link_tag   "layout", :media => "all" 
    = stylesheet_link_tag   "nivo-slider", :media => "all" 
    = stylesheet_link_tag   'light.css', :media => "all" 
    = javascript_include_tag "application"
    = javascript_include_tag "jquery.nivo.slider"
    = javascript_include_tag "main"

    = csrf_meta_tags
  body
    div.center
      div#header
		a[href='/']: img[src='/assets/common/logo.png']
		div.right
		   =form_tag(main_search_path,method:"get",id:'inform') 
		     =text_field_tag(:keyword,'',class:'txt',placeholder:'请输入关键字')
		     =submit_tag('',id:'search')
	div#menu.center  
		ul
		  li[style='border-left:0;width:125px;']: a[href='/'] 首页
		  li: a[href='/news'] 本地资讯
		  li: a[href='/dynamic'] 合作社动态
		  li: a[href='/intro'] 合作社简介
		  li: a[href='/policy'] 政策法规
		  li: a[href='/supply'] 供求信息
		  li: a[href='/product'] 产品展示
		  li: a[href='/tech'] 技术资料
    div.center
	  div.slider-wrapper.theme-light
          div#slider.nivoSlider
            -(1..5).each do |index|
              img[src="/assets/common/s#{index}.jpg" data-thumb="/assets/common/s#{index}.jpg"]  
    div.clear
	div.center#main
	  div.left
	    / marquee[width="640" direction="left" scrollamount="2" scrolldelay="1"]
	    /   ul#scroll_news
	    /     -scroll_news.each do |m|
	    /       li: a[href="/detail/#{m.id}"] =m.title
	  / div.right
	  /   =form_tag(main_search_path,method:"get",id:'inform') 
	  /     =text_field_tag(:keyword,'',class:'txt',placeholder:'请输入关键字')
	  /     =submit_tag('',id:'search')
	  div.clear
      = yield 
      div#con11.con
        div.bar 友情链接
        ul
          -Post.where({:typecd=>'LINK'}).each do |p| 
            li: a[href="#{p.val1}" target='_blank'] =p.title 
      div#footer
	    p 主管单位：四川雅安市名山区 备案号：川ICP备203004595号
	    p 运营维护：四川农业大学  电话：103641248047
javascript:
  $(window).load(function() {
	  $('#slider').nivoSlider({
	    effect:'sliceDownLeft,sliceDown,sliceUpDownLeft,sliceUpDown',
	  });
	  $('#menu li:eq(#{@menu})').addClass('on')
  });